# Dev Configurations

#Auto Discovery

api:
  id: "19407955"
  name: ${project.name}
  version: ${project.version}

# Listener Configuration

http:
  port: "8081"
  host: "0.0.0.0" 
  listener:
    basePath: "/micorp-prc-api/v1/*"
  connectionIdleTimeout: "60000"
  reconnection:
    frequency: "2000"
    attempts: "5" 
    
# Requester Configuration
micorp-sys-api:
  port: "443"
  host: "ag-micorp-sys-api-dev-birthh.jit1x7-1.sgp-s1.cloudhub.io" 
  basePath: "/micorp-sys-api/v1"
  postCustomer: "/customers"
  postOrder: "/orders"
  postItems: "/items"
  response:
    timeout: "90000"
  reconnection:
    frequency: "2000"
    attempts: "5" 


# JSON Logger Configurations

json:
  logger:
    application:
      name: ${project.name}
      version: ${project.version}
      disabledFields: "content"
      maskedFields: "client_id,client_secret"
 
