# Dev Secure Credentials

# Micorp System API Client Id and Client Secret
headers:
  client_id: "![i1ao5U5Y+c0T2R2GFQ+6JG2PTbDPiUxkfkW7feCx+qzZ1YgV9jFMfw==]" 
  client_secret: "![DVdQSYYgEhWsobO7AfyDC7a+Ehe7tuCucjTxe8yzsiM8LbYmDMG1Iw==]"